spring.application.name=movie-diary

server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://localhost:3306/movie_diary?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

tmdb.api.key=288aec03abb40aa1b69c2dfe6d3ea972
tmdb.base.url=https://api.themoviedb.org/3

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

