spring.application.name=movie-diary

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
spring.jpa.properties.hibernate.format_sql=true

tmdb.api.key=288aec03abb40aa1b69c2dfe6d3ea972
tmdb.base.url=https://api.themoviedb.org/3

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

